import ts from 'typescript';
import {mkdtemp, readFile, writeFile, rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {pathToFileURL} from 'node:url';
import assert from 'node:assert/strict';
const dir=await mkdtemp(join(tmpdir(),'vteam-test-'));
try{
 for(const name of ['model','operations']){
 const source=await readFile(new URL(`../lib/${name}.ts`,import.meta.url),'utf8');
 const code=ts.transpileModule(source,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ES2022}}).outputText.replaceAll("'./model'","'./model.mjs'");
 await writeFile(join(dir,`${name}.mjs`),code);
 }
 const {seedWorkspace,projection,counts,DEMO_MEMBER,upgradeWorkspace,courtSlots,deadlineLabel,kstDate,attendanceStep,priorityActive,effectiveRole}=await import(pathToFileURL(join(dir,'model.mjs')));
 const {operate}=await import(pathToFileURL(join(dir,'operations.mjs')));
 const now=Date.parse('2026-09-22T02:00:00Z');let passed=0;
 function check(name,run){run();passed++;console.log(`PASS ${name}`)}
 const seed=()=>seedWorkspace(new Date(now));
 const act=(w,a,role='master',n=now)=>operate(w,{sessionId:'s1',...a},role,n);
 check('upper limit sends a new response to candidate',()=>{const w=seed();w.sessions[0].cap=21;const u=act(w,{type:'respond',response:'yes'},'member');assert.equal(u.sessions[0].participants.find(p=>p.memberId===DEMO_MEMBER).category,'candidate');assert.equal(counts(u.sessions[0]).regular,21)});
 check('deadline blocks absence but accepts candidate',()=>{const w=seed();w.sessions[0].phase='candidates';assert.throws(()=>act(w,{type:'respond',response:'no'},'member'));assert.equal(act(w,{type:'respond',response:'yes'},'member').sessions[0].participants.at(-1).category,'candidate')});
 check('candidate stops at exact exercise start',()=>{const w=seed();assert.throws(()=>act(w,{type:'respond',response:'yes'},'member',Date.parse(w.sessions[0].start)))});
 check('staff cannot proxy while chair and master can',()=>{const w=seed();assert.throws(()=>act(w,{type:'proxy',memberId:'m24'},'staff'));for(const r of ['master','chair'])assert.ok(act(w,{type:'proxy',memberId:'m24'},r).sessions[0].participants.find(p=>p.memberId==='m24'))});
 check('proxy plus self response cannot duplicate membership',()=>{const w=act(seed(),{type:'proxy',memberId:DEMO_MEMBER});const u=act(w,{type:'respond',response:'yes'},'member');assert.equal(u.sessions[0].participants.filter(p=>p.memberId===DEMO_MEMBER).length,1)});
 check('new member exception requires leader and retains type',()=>{const w=seed();assert.throws(()=>act(w,{type:'assign',participantId:'m27',team:0},'staff'));const u=act(w,{type:'assign',participantId:'m27',team:0},'chair');assert.equal(u.members.find(m=>m.id==='m27').kind,'new');assert.equal(u.sessions[0].participants.find(p=>p.id==='m27').team,0)});
 check('member projection hides roster, evaluation, draft assignment',()=>{let w=act(seed(),{type:'proxy',memberId:DEMO_MEMBER});w=act(w,{type:'assign',participantId:DEMO_MEMBER,team:0});const v=projection(w,'member',DEMO_MEMBER,0);assert.deepEqual(v.members,[]);assert.equal(v.sessions[0].participants.length,1);assert.equal(v.sessions[0].participants[0].team,null);assert.equal(v.sessions[0].participants[0].at,'');assert.equal(v.sessions[0].participants[0].position,undefined);assert.deepEqual(Object.keys(v.sessions[0].counts).sort(),['candidate','regular','total'])});
 check('published names and positions contain no evaluation or times',()=>{const w=act(seed(),{type:'publish'});const pub=projection(w,'member',DEMO_MEMBER,0).sessions[0].published;assert.equal(pub.people.length,21);assert.ok(pub.people.every(p=>!('level' in p)&&!('at' in p)&&!('source' in p)));assert.equal(pub.people[0].name,[...pub.people].sort((a,b)=>a.name.localeCompare(b.name,'ko'))[0].name)});
 check('draft changes do not alter the last published snapshot',()=>{let w=act(seed(),{type:'publish'});const before=JSON.stringify(w.sessions[0].published);w=act(w,{type:'assign',participantId:'m1',team:0});assert.equal(JSON.stringify(w.sessions[0].published),before)});
 check('guest removal removes exactly one record',()=>{let w=act(seed(),{type:'guest',name:'테스트 게스트'});const g=w.sessions[0].participants.at(-1);w=act(w,{type:'removeGuest',participantId:g.id});assert.equal(w.sessions[0].participants.length,21);assert.ok(w.sessions[0].participants.some(p=>p.id==='m1'))});
 check('next week does not copy people or published results',()=>{let w=act(seed(),{type:'guest',name:'게스트'});w=act(w,{type:'publish'});w=act(w,{type:'clone'});assert.equal(w.sessions.at(-1).participants.length,0);assert.equal(w.sessions.at(-1).published,null);assert.equal(w.sessions.at(-1).phase,'draft')});
 check('setter role and seat persist independently of profile',()=>{let w=act(seed(),{type:'position',participantId:'m1',position:'S',setterSeat:'MB'});assert.equal(w.members[0].main,'S');assert.equal(w.sessions[0].participants[0].setterSeat,'MB')});
 check('member and staff cannot edit club defaults',()=>{for(const r of ['member','staff'])assert.throws(()=>act(seed(),{type:'club'},r))});
 check('seven-player team permits repeated positions',()=>{let w=act(seed(),{type:'template',teamCount:3,teamSize:7});for(let i=1;i<=7;i++){w=act(w,{type:'assign',participantId:`m${i}`,team:0});w=act(w,{type:'position',participantId:`m${i}`,position:'OH'})}assert.equal(w.sessions[0].participants.filter(p=>p.team===0).length,7)});
 check('session date validation and member write restrictions',()=>{assert.throws(()=>act(seed(),{type:'saveSession',start:'bad',end:'bad',deadline:'bad'}));assert.throws(()=>act(seed(),{type:'publish'},'member'));assert.throws(()=>act(seed(),{type:'post',category:'notice',title:'a',body:'b'},'member'))});
 check('both clubs keep entry, warm-up and play times separate',()=>{const a=seedWorkspace(new Date(now),'seoul-demo'),b=seedWorkspace(new Date(now),'heroes');assert.equal(a.club.name,'뉴배동');assert.equal(b.club.name,'히어로즈');for(const w of [a,b])assert.equal(Date.parse(w.sessions[0].start)-Date.parse(w.sessions[0].entry),30*60000);assert.equal(new Date(Date.parse(a.sessions[0].start)+9*3600000).getUTCDay(),0);assert.equal(new Date(Date.parse(b.sessions[0].start)+9*3600000).getUTCDay(),6)});
 check('new club week uses its own Saturday time and does not copy participants',()=>{const w=seedWorkspace(new Date(now),'heroes');const n=act(w,{type:'clone'});const added=n.sessions.at(-1);assert.equal(new Date(Date.parse(added.start)+9*3600000).getUTCDay(),6);assert.ok(added.start.endsWith('05:00:00.000Z'));assert.ok(added.entry.endsWith('04:30:00.000Z'));assert.equal(added.participants.length,0)});
 check('legacy upgrade keeps responses, post content and public snapshot',()=>{let w=act(seed(),{type:'publish'});delete w.schemaVersion;w.club.name='사이드아웃 서울';const before=JSON.stringify(w.sessions[0].published);const n=upgradeWorkspace(w);assert.equal(n.club.name,'뉴배동');assert.equal(n.sessions[0].participants.length,w.sessions[0].participants.length);assert.equal(JSON.stringify(n.sessions[0].published),before);assert.deepEqual(n.posts,w.posts);assert.deepEqual(upgradeWorkspace(n),n)});
 check('placing a player fills one slot and moving frees the original',()=>{let w=act(seed(),{type:'place',participantId:'m1',team:0,slot:'OP2'});w=act(w,{type:'place',participantId:'m1',team:1,slot:'OP2'});const p=w.sessions[0].participants.find(x=>x.id==='m1');assert.equal(p.team,1);assert.equal(p.position,'S');assert.equal(p.setterSeat,'OP');assert.equal(w.sessions[0].participants.filter(x=>x.team===0&&x.slot==='OP2').length,0)});
 check('occupied slots reject replacement without dropping anyone',()=>{let w=act(seed(),{type:'place',participantId:'m1',team:0,slot:'OP2'});assert.throws(()=>act(w,{type:'place',participantId:'m2',team:0,slot:'OP2'}));assert.equal(w.sessions[0].participants.find(x=>x.id==='m1').team,0);assert.equal(w.sessions[0].participants.find(x=>x.id==='m2').team,null)});
 check('full member picker performs proxy and placement atomically for leaders',()=>{const w=seed();assert.throws(()=>act(w,{type:'place',memberId:'m25',team:0,slot:'OH1'},'staff'));const n=act(w,{type:'place',memberId:'m25',team:0,slot:'OH1'},'chair');const p=n.sessions[0].participants.find(p=>p.memberId==='m25');assert.equal(p.source,'proxy');assert.equal(p.team,0);assert.equal(p.slot,'OH1')});
 check('special participant placement remains leader-only',()=>{assert.throws(()=>act(seed(),{type:'place',participantId:'m27',team:0,slot:'OH1'},'staff'));assert.equal(act(seed(),{type:'place',participantId:'m27',team:0,slot:'OH1'},'chair').members.find(m=>m.id==='m27').kind,'new')});
 check('setter court template has six distinct slots in both variants',()=>{for(const seat of ['OP','MB']){const slots=courtSlots(seat);assert.equal(new Set(slots.map(s=>s.id)).size,6);assert.equal(slots.filter(s=>s.position==='S').length,1);assert.equal(slots.find(s=>s.position==='S').seat,seat)}});
 check('formation changes cannot silently reassign occupied slots',()=>{const w=act(seed(),{type:'place',participantId:'m1',team:0,slot:'OP2'});assert.throws(()=>act(w,{type:'formation',team:0,seat:'MB'}));const n=act(seed(),{type:'formation',team:0,seat:'MB'});const u=act(n,{type:'place',participantId:'m1',team:0,slot:'MB2'});assert.equal(u.sessions[0].participants[0].setterSeat,'MB')});
 check('deadline D-day uses Korea calendar dates and exact cutoff',()=>{assert.equal(deadlineLabel('2026-09-23T03:00:00Z',now),'D-1');assert.equal(deadlineLabel('2026-09-22T03:00:00Z',now),'D-DAY');assert.equal(deadlineLabel('2026-09-22T02:00:00Z',now),'마감')});
 check('member sees only same-club names and no profile or signup order',()=>{const w=seed();const v=projection(w,'member',DEMO_MEMBER,0),roster=v.sessions[0].roster;assert.ok(roster.length>0);for(const p of roster){assert.deepEqual(Object.keys(p).sort(),['id','name']);assert.equal(w.members.find(m=>m.id===p.id).homeClubId,'seoul-demo')}assert.deepEqual(roster,[...roster].sort((a,b)=>a.name.localeCompare(b.name,'ko')))});
 check('external and unaffiliated members see totals but not applicant names',()=>{for(const club of ['heroes',null]){const w=seed();w.members.find(m=>m.id===DEMO_MEMBER).homeClubId=club;const v=projection(w,'member',DEMO_MEMBER,0);assert.equal(v.sessions[0].roster,undefined);assert.equal(v.sessions[0].counts.total,21);assert.deepEqual(v.members,[])}});
 check('chair and staff have no admin permissions in another club',()=>{const w=seedWorkspace(new Date(now),'heroes');for(const role of ['chair','staff']){assert.equal(effectiveRole(w,role),'member');assert.deepEqual(projection(w,role,DEMO_MEMBER,0).members,[]);assert.throws(()=>act(w,{type:'publish'},role))}});
 check('priority gives home regular member a persistent guarantee even over cap',()=>{const w=seed();w.sessions[0].priorityUntil=new Date(now+3600000).toISOString();w.sessions[0].cap=1;let u=act(w,{type:'respond',response:'yes'},'member');const p=u.sessions[0].participants.find(p=>p.id===DEMO_MEMBER);assert.equal(p.guaranteed,true);assert.equal(p.category,'regular');assert.throws(()=>act(u,{type:'publish'}),/우선 편성/);u=act(u,{type:'assign',participantId:DEMO_MEMBER,team:0});const published=act(u,{type:'publish'},'master',now+7200000);assert.equal(published.sessions[0].participants.find(p=>p.id===DEMO_MEMBER).guaranteed,true)});
 check('external member may sign up during priority but receives no guarantee',()=>{const w=seedWorkspace(new Date(now),'heroes');w.sessions[0].priorityUntil=new Date(now+3600000).toISOString();const u=act(w,{type:'respond',response:'yes'},'member');assert.equal(u.sessions[0].participants.find(p=>p.id===DEMO_MEMBER).guaranteed,false)});
 check('priority closes at exact boundary and cancellation revokes guarantee',()=>{const w=seed();w.sessions[0].priorityUntil=new Date(now+3600000).toISOString();const u=act(w,{type:'respond',response:'yes'},'member');const cancelled=act(u,{type:'respond',response:'no'},'member');assert.equal(cancelled.sessions[0].participants.find(p=>p.id===DEMO_MEMBER).guaranteed,false);assert.equal(act(cancelled,{type:'respond',response:'yes'},'member',now+3600000).sessions[0].participants.find(p=>p.id===DEMO_MEMBER).guaranteed,false)});
 check('new members keep their explicit regular-team exception',()=>{const w=seed();w.members.find(m=>m.id===DEMO_MEMBER).kind='new';w.sessions[0].priorityUntil=new Date(now+3600000).toISOString();assert.equal(act(w,{type:'respond',response:'yes'},'member').sessions[0].participants.find(p=>p.id===DEMO_MEMBER).guaranteed,false)});
 check('legacy migration never grants retroactive guarantees or drops applicants',()=>{const w=seed();w.schemaVersion=2;for(const m of w.members)delete m.homeClubId;const migrated=upgradeWorkspace(w);assert.equal(migrated.sessions[0].participants.length,21);assert.equal(migrated.members.find(m=>m.id===DEMO_MEMBER).homeClubId,'seoul-demo');assert.ok(migrated.sessions[0].participants.every(p=>!p.guaranteed));assert.deepEqual(upgradeWorkspace(migrated),migrated)});
 check('attendance milestones show only the next shortfall',()=>{assert.equal(attendanceStep(0).label,'18명까지 18명');assert.equal(attendanceStep(17).label,'18명까지 1명');assert.equal(attendanceStep(18).label,'21명까지 3명');assert.equal(attendanceStep(20).label,'21명까지 1명');assert.equal(attendanceStep(21).label,'24명까지 3명');assert.equal(attendanceStep(27).label,'28명까지 1명');assert.equal(attendanceStep(30).progress,100)});
 check('priority end cannot be after application deadline',()=>{const w=seed(),s=w.sessions[0];assert.throws(()=>act(w,{type:'saveSession',...s,sessionId:s.id,priorityUntil:s.start}),/우선 신청/)});
 console.log(`${passed} domain checks passed`);
}finally{await rm(dir,{recursive:true,force:true})}
