import {afterEach,it,expect} from 'vitest';
import type {HomeView,SessionDetailView} from '../lib/sideout/read-model';
import {queryFixture} from './helpers/sideout-fixture';
import {ids,session,roster,clubs} from './fixtures/sideout';
import {handleSideoutRead} from '../lib/server/sideout-http';
const opened:Awaited<ReturnType<typeof queryFixture>>[]=[];
async function fixture(){const f=await queryFixture();opened.push(f);return f}
afterEach(()=>opened.splice(0).forEach(f=>f.close()));
it.each(['applicant','guest','master','operator','multi'] as const)('permits published view for %s only through verified identity',async role=>{const f=await fixture();const r=await handleSideoutRead(await f.request(ids[role]),'session',f.deps,session.id);expect(r.status).toBe(200);const {data}=await r.json() as {data:SessionDetailView};expect(data.publishedTeams![0].players).toHaveLength(2);expect(JSON.stringify(data)).not.toMatch(/passwordHash|loginId|grants|firstPublishedAt|draftMatches/)});
it.each(['waiter','outsider','cancelled'] as const)('withholds published lineup and matches from %s',async role=>{const f=await fixture();const r=await handleSideoutRead(await f.request(ids[role]),'session',f.deps,session.id);const {data}=await r.json() as {data:SessionDetailView};expect(data.publishedTeams).toBeNull();expect(data.publishedMatches).toBeNull();expect(data.counts).toEqual({applicants:2,waiting:1})});
it('returns only home applicants and guest count to an ordinary home member',async()=>{const f=await fixture();const {data}=await (await handleSideoutRead(await f.request(),'session',f.deps,session.id)).json() as {data:HomeView & SessionDetailView};expect(data.visibleApplicants.map((m:{memberId:string})=>m.memberId)).toEqual([ids.applicant]);expect(data.guestCount).toBe(1);expect(Object.values(data.capabilities).every(v=>v===false)).toBe(true);expect(data).not.toHaveProperty('waiters')});
it('a guest sees published lineup but no club applicant directory',async()=>{const f=await fixture();const {data}=await (await handleSideoutRead(await f.request(ids.guest),'session',f.deps,session.id)).json() as {data:HomeView & SessionDetailView};expect(data.visibleApplicants).toEqual([]);expect(data.guestCount).toBeNull()});
it('draft detail is indistinguishable from a missing ID; role query cannot escalate',async()=>{const f=await fixture();const req=await f.request(ids.applicant,'http://local/?role=master');const a=await handleSideoutRead(req,'session',f.deps,'hidden'),b=await handleSideoutRead(req,'session',f.deps,'absent');expect(a.status).toBe(404);expect(await a.json()).toEqual(await b.json());const {data}=await (await handleSideoutRead(req,'sessions',f.deps)).json() as {data:HomeView & SessionDetailView};expect(data.cards.map((c:{session:{id:string}})=>c.session.id)).toEqual([session.id]);expect(data.registrationOpportunities).toEqual([])});
it('manager sees prepared sessions and only permitted registration opportunities',async()=>{const f=await fixture();const {data}=await (await handleSideoutRead(await f.request(ids.multi),'sessions',f.deps)).json() as {data:HomeView & SessionDetailView};expect(data.cards).toHaveLength(2);expect(data.cards.every((c:{canManage:boolean})=>c.canManage)).toBe(true)});
it('identity lookup retains separate IDs after rename or deactivation',async()=>{const f=await fixture();f.sqlite.prepare('UPDATE auth_members SET display_name=?,active=0 WHERE id=?').run('변경된 이름',ids.guest);const {data}=await (await handleSideoutRead(await f.request(),'session',f.deps,session.id)).json() as {data:HomeView & SessionDetailView};expect(data.publishedTeams![0].players.map((p:{displayName:string})=>p.displayName)).toEqual(['동명이인','변경된 이름'])});
it('unknown filters and orphan references fail rather than fabricate data',async()=>{const f=await fixture();expect((await handleSideoutRead(await f.request(ids.master,'http://local/?filter=missing'),'sessions',f.deps)).status).toBe(400);f.put('roster',session.id,{...roster,published:{teams:[{id:'team-a',title:'A',players:[{memberId:'missing',slotId:'s',assignedPosition:'S'}]}]}});expect((await handleSideoutRead(await f.request(),'session',f.deps,session.id)).status).toBe(503)});
it('favorites filter uses the current member preference only',async()=>{const f=await fixture();f.put('preferences',ids.applicant,{favoriteClubIds:[clubs[0].id]});for(const [id,count] of [[ids.applicant,1],[ids.guest,0]] as const){const {data}=await (await handleSideoutRead(await f.request(id,'http://local/?filter=favorites'),'sessions',f.deps)).json() as {data:HomeView & SessionDetailView};expect(data.cards.length).toBe(count)}});
