'use client';
import { useState, useEffect, useCallback, type FormEvent, type ReactNode, type CSSProperties } from 'react';
import { CalendarDays, Clock3, MapPin, Volleyball, ArrowUpRight, Check, UsersRound, LayoutDashboard, MessageSquare, SlidersHorizontal, UserRound, Plus, ChevronRight, ChevronLeft, LockKeyhole, Megaphone, Pin, X, Search, RefreshCw, Copy, Send, NotebookPen, FlaskConical, ArrowLeft, Bell } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { Tabs, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Progress } from '@/components/ui/progress';
import { EnrollmentHome, EnrollmentCard } from './enrollment';
import { TeamBoard } from './team-board';
import { Switch } from '@/components/ui/switch';
import { SidebarProvider, Sidebar, SidebarContent, SidebarHeader, SidebarFooter, SidebarMenu, SidebarMenuItem, SidebarMenuButton, SidebarTrigger, SidebarRail, useSidebar } from '@/components/ui/sidebar';
import { Command, CommandInput, CommandList, CommandEmpty, CommandGroup, CommandItem } from '@/components/ui/command';
import { AlertDialog, AlertDialogContent, AlertDialogHeader, AlertDialogTitle, AlertDialogDescription, AlertDialogFooter, AlertDialogCancel } from '@/components/ui/alert-dialog';
import { Toaster } from '@/components/ui/sonner';
import { toast } from 'sonner';
import { stage, publicCounts, counts, positionNames, EXAMPLE_CLUBS, deadlineLabel, type View, type Role, type Session, type Participant, type Member, type Post, type Position } from '@/lib/model';
import type { Action } from '@/lib/operations';
const roleNames:Record<Role,string>={master:'마스터',chair:'회장',staff:'운영진',member:'회원'};
const categories={notice:'공지',event:'이벤트',board:'이야기'};
const format=(date:string,options:Intl.DateTimeFormatOptions={month:'long',day:'numeric',weekday:'long'})=>new Date(date).toLocaleDateString('ko-KR',{timeZone:'Asia/Seoul',...options});
const time=(date:string)=>new Date(date).toLocaleTimeString('ko-KR',{timeZone:'Asia/Seoul',hour:'2-digit',minute:'2-digit',hour12:false});
const localDate=(date:string)=>new Date(Date.parse(date)+9*3600000).toISOString().slice(0,16);
const toISO=(value:FormDataEntryValue|null)=>new Date(`${value}:00+09:00`).toISOString();
const statusNames:Record<string,string>={draft:'준비 중',open:'모집 중',candidates:'후보 접수',closed:'접수 종료',ended:'운동 종료',cancelled:'운동 취소'};
const teamNames=['A','B','C','D','E','F'];
const teamColors=['#60967e','#7596b1','#c3a369','#a58cac','#7c9795','#ac8c86'];
function Picker({value,onChange,items,label,disabled,className}:{value:string;onChange:(v:string)=>void;items:{value:string;label:string}[];label:string;disabled?:boolean;className?:string}){return <Select value={value} onValueChange={onChange} disabled={disabled}><SelectTrigger aria-label={label} className={className}><SelectValue/></SelectTrigger><SelectContent>{items.map(i=><SelectItem value={i.value} key={i.value}>{i.label}</SelectItem>)}</SelectContent></Select>}
function Empty({title,children}:{title:string;children?:ReactNode}){return <div className="empty"><UsersRound/><strong>{title}</strong><p>{children}</p></div>}
function Field({label,children}:{label:string;children:ReactNode}){return <label className="field">{label}{children}</label>}
function Status({s}:{s:Session}){return <span className={`pill ${stage(s)==='open'?'active':stage(s)==='candidates'?'candidate':''}`}>{statusNames[stage(s)]}</span>}
export default function CourtApp(){
 const [role,setRole]=useState<Role>('member');const [clubId,setClubId]=useState('seoul-demo');const [catalog,setCatalog]=useState<Record<string,View>>({});const [nextClub,setNextClub]=useState('seoul-demo');const [view,setView]=useState<View|null>(null);const [page,setPage]=useState('home');const [sessionId,setSessionId]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [modal,setModal]=useState<string|null>(null);const [post,setPost]=useState<Post|null>(null);const [boardTab,setBoardTab]=useState('all');const [calendar,setCalendar]=useState(false);const [month,setMonth]=useState(new Date());
 const load=useCallback(async(signal?:AbortSignal)=>{setError('');try{const entries=await Promise.all(EXAMPLE_CLUBS.map(async club=>{const res=await fetch(`/api/workspace?role=${role}&club=${club.id}`,{signal});const data=await res.json() as View&{error?:string};if(!res.ok)throw new Error(data.error);return [club.id,data] as const}));const views=Object.fromEntries(entries);setCatalog(views);setView(views[clubId]);}catch(e){if((e as Error).name!=='AbortError')setError((e as Error).message)}},[role,clubId]);
 useEffect(()=>{const abort=new AbortController();setView(null);void load(abort.signal);return()=>abort.abort()},[load]);
 // Re-evaluate cutoffs even if the page is kept open.
 const [,tick]=useState(0);useEffect(()=>{const id=setInterval(()=>tick(x=>x+1),30000);return()=>clearInterval(id)},[]);
 useEffect(()=>{if(role!=='member'||busy)return;const refresh=()=>{if(!document.hidden)void load()};const timer=setInterval(refresh,30000);window.addEventListener('focus',refresh);return()=>{clearInterval(timer);window.removeEventListener('focus',refresh)}},[role,busy,load]);
 const s=view?.sessions.find(x=>x.id===sessionId)??view?.sessions.find(x=>!['ended','cancelled'].includes(x.phase))??view?.sessions[0];
 const admin=(view?.role??role)!=='member',leader=(view?.role??role)==='master'||(view?.role??role)==='chair';
 async function act(action:Action,message='저장했어요.',targetClub=clubId){
  if(!view||busy)return false;setBusy(true);setError('');try{const res=await fetch(`/api/workspace?role=${role}&club=${targetClub}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({revision:(catalog[targetClub]??view).revision,accountRevision:view.accountRevision,directoryRevision:view.directoryRevision,action})});const data=await res.json() as View & {error?:string};if(!res.ok){if(res.status===409)await load();throw new Error(data.error)}setCatalog(current=>({...current,[targetClub]:data}));if(targetClub===clubId)setView(data);else if(action.type==='clone'){setClubId(targetClub);setSessionId('')}if(['account','registerMember'].includes(action.type))await load();toast.success(message);return true}catch(e){setError((e as Error).message);toast.error((e as Error).message);return false}finally{setBusy(false)}
 }
 function navigate(p:string){setPage(p);setError('')}
 function changeClub(id:string){setSessionId('');setClubId(id)}
 function prepareNext(){setNextClub(clubId);if(role==='master')setModal('next');else if(s)void act({type:'clone',sessionId:s.id},'다음 회차를 준비 상태로 만들었어요.')}
 const links=[{id:'home',name:'모임 홈',icon:LayoutDashboard},{id:'schedule',name:'운동 일정',icon:CalendarDays},{id:'board',name:'모임 소식',icon:MessageSquare},{id:'notifications',name:'전체 알림',icon:Bell},...(role==='master'?[{id:'members',name:'회원 등록',icon:UsersRound}]:[]),...(admin?[{id:'teams',name:'팀 편성',icon:UsersRound},{id:'settings',name:'운영 설정',icon:SlidersHorizontal}]:[{id:'profile',name:'내 신청',icon:UserRound}])];
 const title=page==='home'?'이번 주, 어느 코트에서 만날까요?':page==='event'?'운동 상세':page==='members'?'회원 등록':page==='notifications'?'전체 알림':page==='schedule'?'우리의 운동 일정':page==='teams'?'이번 운동, 팀을 만들어요.':page==='board'?'코트 밖의 이야기':page==='settings'?'모임 운영 설정':page==='account'?'내 계정':'나의 운동';
 const description=page==='home'?'다가오는 운동을 확인하고, 함께할 시간을 선택하세요.':page==='event'?'선택한 운동의 신청 상태를 확인하세요.':page==='members'?'회원 등록 시 소속을 지정해 주세요.':page==='notifications'?'새로운 소식을 확인해요.':page==='schedule'?'다가오는 운동부터 지난 기록까지.':page==='teams'?'참여 인원을 확인하고 각 팀에 알맞게 배정해요.':page==='board'?'공지와 소식, 함께 나누고 싶은 이야기.':page==='settings'?'회차별 모집과 우리 모임의 기본 정보를 관리해요.':page==='account'?'내 정보를 확인하고 수정해요.':'신청 상태와 공개된 팀을 확인해요.';
 const sortedPosts=view?[...view.posts].sort((a,b)=>Number(b.pinned)-Number(a.pinned)||Date.parse(b.at)-Date.parse(a.at)):[];
 return <SidebarProvider style={{'--sidebar-width':'208px','--sidebar-width-icon':'64px'} as CSSProperties}><SideNavigation view={view} role={role} setRole={r=>{setRole(r);setPage('home')}} page={page} links={links} navigate={navigate} clubId={clubId} changeClub={changeClub} busy={busy}/><div className="content-shell"><div className="mobile-menu-entry"><SidebarTrigger aria-label="메뉴 열기"/><span>메뉴</span></div><main className="main"><div className="page-heading"><div><h1>{title}</h1><p className="muted">{description}</p></div>{page==='board'?<Button onClick={()=>setModal('post')}><Plus size={17}/> 글 쓰기</Button>:(page==='schedule'||page==='home')&&admin&&s?<Button variant="outline" onClick={prepareNext} disabled={busy}><Plus size={17}/> 다음 주 준비</Button>:null}</div>{error&&<div role="alert" className="error mb-5 inline-actions"><span className="grow">{error}</span><Button variant="outline" size="sm" onClick={()=>void load()}><RefreshCw size={14}/> 새로고침</Button></div>}{!view?<div className="loading"><Volleyball/><p>{error?'연결을 다시 확인해 주세요.':'모임을 불러오고 있어요.'}</p></div>:<>
 {page==='home'&&<EnrollmentHome catalog={catalog} busy={busy} respond={(club,event,response)=>void act({type:'respond',sessionId:event.id,response},response==='yes'?'참석 신청되었습니다.':'참석이 취소되었습니다.',club)} manage={(club,event)=>{changeClub(club);setSessionId(event.id);navigate('teams')}} teams={(event,id)=><PublishedTeams s={event} memberId={id}/>}/>}
 {['schedule','teams','settings','board','profile'].includes(page)&&<div className="management-bar"><Picker value={clubId} label="조회할 모임" disabled={busy} onChange={changeClub} items={EXAMPLE_CLUBS.map(c=>({value:c.id,label:catalog[c.id]?.club.name??c.name}))}/></div>}
 {page==='event'&&s&&<div className="event-detail"><EnrollmentCard view={view} s={s} busy={busy} respond={response=>void act({type:'respond',sessionId:s.id,response},response==='yes'?'참석 신청되었습니다.':'참석이 취소되었습니다.')} manage={()=>navigate('teams')} teams={(event,id)=><PublishedTeams s={event} memberId={id}/>}/></div>}
 {page==='notifications'&&<><section className="panel"><h2>서비스 알림</h2><p className="helper">새로운 서비스 알림이 없어요.</p></section>{Object.values(catalog).flatMap(v=>v.sessions.filter(x=>x.published&&x.participants.some(p=>p.memberId===v.memberId&&p.response==='yes')).map(x=><button className="schedule-row mt-4" key={v.club.id+x.id} onClick={()=>{changeClub(v.club.id);setSessionId(x.id);navigate('event')}}><Bell size={20}/><span>{v.club.name} · {format(x.start,{month:'numeric',day:'numeric'})} 팀편성이 공개되었어요.</span><ChevronRight size={18}/></button>))}</>}
 {page==='members'&&role==='master'&&<MemberRegistration view={view} busy={busy} act={act}/>}
 {page==='profile'&&<div className="schedule-list">{view.sessions.map(item=>{const me=item.participants.find(p=>p.memberId===view.memberId);return <button key={item.id} className="schedule-row" onClick={()=>{setSessionId(item.id);navigate('event')}}><span className="date-block"><span>{format(item.start,{month:'long'})}</span><strong>{format(item.start,{day:'numeric'}).replace('일','')}</strong></span><span className="grow"><h3>{item.title}</h3><p>{time(item.start)} · {item.location}</p></span><span className="pill">{!me?'미응답':me.response==='no'?'불참':me.category==='candidate'?'후보 신청':'참석 신청'}</span></button>})}</div>}
 {page==='schedule'&&<><div className="management-bar"><Tabs value={calendar?'calendar':'list'} onValueChange={v=>setCalendar(v==='calendar')}><TabsList><TabsTrigger value="list">일정 목록</TabsTrigger><TabsTrigger value="calendar">달력</TabsTrigger></TabsList></Tabs></div>{calendar?<CalendarView month={month} setMonth={setMonth} sessions={view.sessions} onSelect={id=>{setSessionId(id);navigate('event')}}/>:<div className="schedule-list">{[...view.sessions].sort((a,b)=>Date.parse(b.start)-Date.parse(a.start)).map(item=><button className="schedule-row" key={item.id} onClick={()=>{setSessionId(item.id);navigate('event')}}><span className="date-block"><span>{format(item.start,{month:'long'})}</span><strong>{format(item.start,{day:'numeric'}).replace('일','')}</strong></span><span className="grow"><h3>{item.title}</h3><p>{time(item.start)}–{time(item.end)} · {item.location}</p></span><Status s={item}/><ChevronRight size={20}/></button>)}</div>}</>}
 {page==='board'&&<><Tabs value={boardTab} onValueChange={setBoardTab}><TabsList><TabsTrigger value="all">전체 소식</TabsTrigger>{Object.entries(categories).map(([key,name])=><TabsTrigger key={key} value={key}>{name}</TabsTrigger>)}</TabsList></Tabs><div className="board-grid">{sortedPosts.filter(p=>boardTab==='all'||p.category===boardTab).map(p=><button key={p.id} className="panel post-card" onClick={()=>setPost(p)}><div className="inline-actions"><span className="pill">{categories[p.category]}</span>{p.pinned&&<Pin size={14} className="text-primary"/>}</div><h3>{p.title}</h3><p>{p.body.slice(0,120)}{p.body.length>120?'…':''}</p><footer><span>{p.author} · {format(p.at,{month:'long',day:'numeric'})}</span><span className="inline-actions"><MessageSquare size={14}/>{p.comments.length}</span></footer></button>)}</div></>}
 {page==='teams'&&admin&&s&&<TeamBoard key={clubId+':'+s.id} view={view} s={s} busy={busy} act={act} leader={leader} onSession={setSessionId} onPublish={()=>setModal('publish')}/>}
 {page==='account'&&<AccountScreen key={view.accountRevision} view={view} role={role} busy={busy} act={act}/>}
 {page==='settings'&&admin&&s&&<Settings view={view} s={s} busy={busy} act={act} leader={leader} onSession={setSessionId}/>}
 </>}</main></div>
 <Dialog open={modal==='next'} onOpenChange={v=>!v&&setModal(null)}><DialogContent><DialogHeader><DialogTitle>어느 모임의 다음 회차를 준비할까요?</DialogTitle><DialogDescription>선택한 모임의 요일·시간으로 다음 일정을 만들어요. 참석 명단과 팀 배정은 복사되지 않아요.</DialogDescription></DialogHeader><Field label="모임 선택"><Picker label="다음 회차 모임" value={nextClub} onChange={setNextClub} items={EXAMPLE_CLUBS.map(c=>({value:c.id,label:`${c.name} · ${'일월화수목금토'[c.weekday]}요일 ${c.entryTime}`}))}/></Field><p className="helper">{EXAMPLE_CLUBS.find(c=>c.id===nextClub)?.location}</p><Button disabled={busy||!catalog[nextClub]} onClick={async()=>{const source=catalog[nextClub]?.sessions.at(-1);if(source&&await act({type:'clone',sessionId:source.id},'선택한 모임의 다음 회차를 만들었어요.',nextClub)){setModal(null);navigate('schedule')}}}>다음 회차 만들기</Button></DialogContent></Dialog>
 <Dialog open={modal==='publish'} onOpenChange={v=>!v&&setModal(null)}><DialogContent className="dialog-scroll"><DialogHeader><DialogTitle>회원에게 팀 편성을 공개할까요?</DialogTitle><DialogDescription>우선 편성 대상은 모두 팀에 배정해야 공개할 수 있어요. 실력·프로필·신청 순서는 공개하지 않아요.</DialogDescription></DialogHeader>{s&&<><div className="stats-grid grid-cols-2"><div className="stat"><span className="label">팀에 배정</span><strong>{counts(s).assigned}명</strong></div><div className="stat"><span className="label">함께 참여 · 미배정</span><strong>{counts(s).total-counts(s).assigned}명</strong></div></div><p className="helper">{Array.from({length:s.teamCount},(_,i)=>`${teamNames[i]}팀 ${s.participants.filter(p=>p.team===i&&p.response==='yes').length}명`).join(' · ')}</p><Button disabled={busy} onClick={async()=>{if(await act({type:'publish',sessionId:s.id},'팀 편성을 회원에게 공개했어요.'))setModal(null)}}><Send size={16}/> 공개하기</Button></>}</DialogContent></Dialog>
 <Dialog open={modal==='post'} onOpenChange={v=>!v&&setModal(null)}><DialogContent className="dialog-scroll"><DialogHeader><DialogTitle>모임에 소식 남기기</DialogTitle><DialogDescription>우리 모임 회원들과 이야기를 나눠요.</DialogDescription></DialogHeader><PostForm admin={admin} busy={busy} onSubmit={async data=>{if(await act({type:'post',...data},'글을 등록했어요.'))setModal(null)}}/></DialogContent></Dialog>
 <Dialog open={!!post} onOpenChange={v=>!v&&setPost(null)}><DialogContent className="dialog-scroll">{post&&<><DialogHeader><DialogTitle>{post.title}</DialogTitle><DialogDescription>{categories[post.category]} · {post.author}</DialogDescription></DialogHeader><div className="post-body">{post.body}</div><h3 className="font-semibold">댓글</h3>{(view?.posts.find(p=>p.id===post.id)?.comments??[]).map(c=><div key={c.id} className="comment"><strong>{c.author}</strong><small className="ml-3">{format(c.at,{month:'numeric',day:'numeric'})}</small><p>{c.body}</p></div>)}<form className="form-stack" onSubmit={async e=>{e.preventDefault();const form=e.currentTarget;const body=new FormData(form).get('body');if(await act({type:'comment',postId:post.id,body},'댓글을 남겼어요.'))form.reset()}}><Textarea name="body" aria-label="댓글" placeholder="함께 나눌 이야기를 적어 주세요." required maxLength={2000}/><Button disabled={busy} type="submit">댓글 등록</Button></form></>}</DialogContent></Dialog><Toaster richColors position="bottom-right" theme="light"/></SidebarProvider>
}
function PublishedTeams({s,memberId}:{s:Session;memberId:string}){if(!s.published)return null;return <section className="public-teams"><div className="section-heading"><h2>우리의 팀</h2><span className="live-tag">{format(s.published.at,{month:'numeric',day:'numeric'})} {time(s.published.at)} 공개</span></div><div className="team-grid">{Array.from({length:s.published.teams},(_,i)=><article className="team-card" key={i} style={{'--team-color':teamColors[i]} as CSSProperties}><header><h3>{teamNames[i]} TEAM</h3><span>{s.published!.people.filter(p=>p.team===i).length}명</span></header><div className="team-body">{s.published!.people.filter(p=>p.team===i).map(p=><div className="team-member" key={p.id}><strong>{p.name} {p.id===memberId&&<span className="pill active">나</span>}</strong>{p.position&&<span className="player-position">{positionNames[p.position]}{p.position==='S'?` · ${p.setterSeat==='MB'?'센터':'라이트'} 자리`:''}</span>}</div>)}</div>{s.published!.teamSize===7&&<footer>6명 플레이 · 1명씩 돌아가며 휴식</footer>}</article>)}</div><div className="panel mt-5"><h3>함께 참여하는 사람들</h3><div className="public-name-list">{s.published.people.filter(p=>p.team===null).map(p=><span key={p.id}>{p.name}</span>)}{s.published.people.every(p=>p.team!==null)&&<p className="helper">모든 참여 인원이 팀에 배정되어 있어요.</p>}</div></div></section>}
function CalendarView({month,setMonth,sessions,onSelect}:{month:Date;setMonth:(d:Date)=>void;sessions:Session[];onSelect:(id:string)=>void}){const y=month.getFullYear(),m=month.getMonth(),offset=new Date(y,m,1).getDay(),days=new Date(y,m+1,0).getDate();return <div className="panel"><div className="calendar-tools"><Button variant="ghost" size="icon" aria-label="이전 달" onClick={()=>setMonth(new Date(y,m-1,1))}><ChevronLeft/></Button><strong>{y}년 {m+1}월</strong><Button variant="ghost" size="icon" aria-label="다음 달" onClick={()=>setMonth(new Date(y,m+1,1))}><ChevronRight/></Button></div><div className="calendar">{'일월화수목금토'.split('').map(d=><div className="calendar-head" key={d}>{d}</div>)}{Array.from({length:offset},(_,i)=><div key={`empty${i}`} className="!bg-transparent !border-0"/>)}{Array.from({length:days},(_,i)=>{const date=`${y}-${String(m+1).padStart(2,'0')}-${String(i+1).padStart(2,'0')}`;return <div key={i}>{i+1}{sessions.filter(s=>localDate(s.start).startsWith(date)).map(s=><button key={s.id} onClick={()=>onSelect(s.id)}>{time(s.start)} 배구</button>)}</div>})}</div></div>}
function PostForm({admin,busy,onSubmit}:{admin:boolean;busy:boolean;onSubmit:(d:Record<string,unknown>)=>void}){const [category,setCategory]=useState(admin?'notice':'board');const [pinned,setPinned]=useState(false);return <form className="form-stack" onSubmit={e=>{e.preventDefault();onSubmit({...Object.fromEntries(new FormData(e.currentTarget)),category,pinned})}}><Field label="게시판"><Picker value={category} onChange={setCategory} label="게시판" items={Object.entries(categories).filter(([k])=>admin||k==='board').map(([value,label])=>({value,label}))}/></Field><Field label="제목"><Input name="title" required maxLength={100}/></Field><Field label="내용"><Textarea name="body" required maxLength={5000} className="min-h-40"/></Field>{admin&&<label className="switch-line text-sm">상단에 고정<Switch checked={pinned} onCheckedChange={setPinned}/></label>}<Button type="submit" disabled={busy}>글 등록</Button></form>}
type EditorProps={view:View;s:Session;busy:boolean;act:(a:Action,m?:string)=>Promise<boolean>;leader:boolean;onSession:(id:string)=>void};
function MemberRegistration({view,busy,act}:{view:View;busy:boolean;act:EditorProps['act']}){
 const [home,setHome]=useState('seoul-demo'),[kind,setKind]=useState('regular');
 return <div className="settings-grid"><section className="panel"><h2>회원 정보 등록</h2><form className="form-stack mt-5" onSubmit={async e=>{e.preventDefault();const form=e.currentTarget;if(await act({type:'registerMember',name:new FormData(form).get('name'),homeClubId:home==='none'?null:home,kind},'회원을 등록했어요.'))form.reset()}}><Field label="이름"><Input name="name" required maxLength={30}/></Field><Field label="소속 모임"><Picker value={home} onChange={setHome} label="회원 소속" items={[...EXAMPLE_CLUBS.map(c=>({value:c.id,label:c.name})),{value:'none',label:'무소속'}]}/></Field><Field label="회원 분류"><Picker value={kind} onChange={setKind} label="회원 분류" items={[{value:'regular',label:'정규 회원'},{value:'new',label:'신입 회원'}]}/></Field><Button disabled={busy} type="submit">회원 등록</Button><p className="helper">등록한 인원은 전체 회원 검색에서 편성할 수 있어요. 로그인 정보 발급은 아직 연결 전입니다.</p></form></section><section className="panel"><h2>등록 회원 {view.members.length}명</h2><div className="member-directory">{view.members.map(m=><div key={m.id}><strong>{m.name}</strong><span>{EXAMPLE_CLUBS.find(c=>c.id===m.homeClubId)?.name??'무소속'} · {m.kind==='new'?'신입':'정규'}</span></div>)}</div></section></div>
}
function ProfileForm({member,busy,onSubmit}:{member:Member;busy:boolean;onSubmit:(fields:Record<string,unknown>)=>void}){const [main,setMain]=useState(member.main),[sub,setSub]=useState(member.sub),[level,setLevel]=useState(member.level?String(member.level):'none');const positions=Object.entries(positionNames).map(([value,label])=>({value,label}));return <form className="form-stack" onSubmit={e=>{e.preventDefault();onSubmit({main,sub,level:level==='none'?null:Number(level)})}}><div className="form-row"><Field label="주 포지션"><Picker label="주 포지션" value={main} onChange={v=>setMain(v as Position)} items={positions}/></Field><Field label="부 포지션"><Picker label="부 포지션" value={sub} onChange={v=>setSub(v as Position)} items={positions}/></Field></div><Field label="운영진 평가"><Picker label="실력 단계" value={level} onChange={setLevel} items={[{value:'none',label:'미평가'},...[1,2,3,4,5].map(n=>({value:String(n),label:`${n}단계`}))]}/></Field><p className="helper">높은 단계일수록 숙련도가 높아요. 배정 참고용이며 회원에게 공개되지 않아요.</p><Button disabled={busy} type="submit">저장</Button></form>}
function Settings({view,s,busy,act,leader,onSession}:EditorProps){const [phase,setPhase]=useState<string|null>(null);return <><div className="management-bar"><Picker label="설정할 운동" value={s.id} onChange={onSession} items={view.sessions.map(x=>({value:x.id,label:`${format(x.start,{month:'numeric',day:'numeric'})} · ${x.title}`}))}/><div className="inline-actions"><Status s={s}/><Button variant="outline" disabled={busy} onClick={()=>void act({type:'clone',sessionId:s.id},'다음 주 회차를 준비 상태로 만들었어요.')}><Copy size={15}/> 다음 주 복사</Button></div></div><div className="settings-grid"><section className="panel"><h3 className="settings-title">이번 운동과 모집</h3><SessionForm key={s.id+':'+s.phase} s={s} busy={busy} act={act}/><div className="section-divider"/><div className="inline-actions">{s.phase==='draft'&&<Button disabled={busy} onClick={()=>void act({type:'phase',sessionId:s.id,phase:'open'},'모집을 열었어요.')}>모집 열기</Button>}{stage(s)==='open'&&<Button variant="outline" disabled={busy} onClick={()=>setPhase('candidates')}>일반 신청 마감</Button>}{!['ended','cancelled','draft'].includes(s.phase)&&<Button variant="outline" disabled={busy} onClick={()=>setPhase('ended')}>운동 종료</Button>}{!['ended','cancelled'].includes(s.phase)&&<Button variant="ghost" disabled={busy} onClick={()=>setPhase('cancelled')}>운동 취소</Button>}</div><p className="helper mt-3">일반 신청 마감 뒤에도 운동 시작 전까지 후보 신청을 받아요.</p></section><section className="panel"><h3 className="settings-title">모임 기본 정보</h3>{leader?<ClubForm view={view} busy={busy} act={act}/>:<><p className="helper">장소·기본 시간 설정은 마스터·회장이 변경할 수 있어요.</p><p className="mt-4">{view.club.location}</p></>}<div className="section-divider"/><p className="helper">로그인 계정 발급과 추가 운영진 지정은 다음 개발 단계에서 연결해요. 추가 운영진은 마스터만 지정할 수 있어요.</p></section></div><AlertDialog open={!!phase} onOpenChange={v=>!v&&setPhase(null)}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>{phase==='candidates'?'일반 신청을 마감할까요?':phase==='ended'?'이번 운동을 종료할까요?':'이번 운동을 취소할까요?'}</AlertDialogTitle><AlertDialogDescription>{phase==='candidates'?'기존 신청의 불참 변경이 잠기고, 새 신청은 후보로 접수돼요.':'회원의 새 신청이 종료되고 지금까지의 기록은 남아요.'}</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>돌아가기</AlertDialogCancel><Button disabled={busy} onClick={async()=>{if(await act({type:'phase',sessionId:s.id,phase},'운동 상태를 변경했어요.'))setPhase(null)}}>확인</Button></AlertDialogFooter></AlertDialogContent></AlertDialog></>}
function SessionForm({s,busy,act}:{s:Session;busy:boolean;act:EditorProps['act']}){const [capped,setCapped]=useState(s.cap!==null);const locked=busy||['ended','cancelled'].includes(s.phase);return <form className="form-stack" onSubmit={e=>{e.preventDefault();const d=new FormData(e.currentTarget);void act({type:'saveSession',sessionId:s.id,title:d.get('title'),location:d.get('location'),address:d.get('address'),note:d.get('note'),start:toISO(d.get('start')),end:toISO(d.get('end')),deadline:toISO(d.get('deadline')),priorityUntil:d.get('priorityUntil')?toISO(d.get('priorityUntil')):null,cap:capped?Number(d.get('cap')):null},'회차 설정을 저장했어요.')}}><Field label="운동 이름"><Input name="title" defaultValue={s.title} required maxLength={60} disabled={locked}/></Field><div className="form-row"><Field label="시작 · 한국 시간"><Input type="datetime-local" name="start" defaultValue={localDate(s.start)} required disabled={locked}/></Field><Field label="종료 · 한국 시간"><Input type="datetime-local" name="end" defaultValue={localDate(s.end)} required disabled={locked}/></Field></div><Field label="소속 회원 우선 신청 종료 · 선택"><Input type="datetime-local" name="priorityUntil" defaultValue={s.priorityUntil?localDate(s.priorityUntil):''} disabled={locked}/></Field><Field label="일반 신청 마감"><Input type="datetime-local" name="deadline" defaultValue={localDate(s.deadline)} required disabled={locked}/></Field><Field label="장소"><Input name="location" defaultValue={s.location} required maxLength={100} disabled={locked}/></Field><Field label="위치 안내"><Input name="address" defaultValue={s.address} maxLength={200} disabled={locked}/></Field><Field label="이번 운동 안내"><Textarea name="note" defaultValue={s.note} maxLength={2000} disabled={locked}/></Field><label className="switch-line text-sm">일반 신청 상한 사용<Switch checked={capped} onCheckedChange={setCapped} disabled={locked}/></label>{capped&&<Field label="일반 신청 인원"><Input type="number" name="cap" defaultValue={s.cap??24} min={1} max={200} required disabled={locked}/></Field>}<p className="helper">상한에 도달해도 후보 신청은 가능해요. 후보·임시 인원은 상한에서 제외합니다. 우선 기간의 정규 소속 회원은 상한과 관계없이 편성 보장 대상입니다.</p><Button type="submit" disabled={locked}>회차 설정 저장</Button></form>}
function ClubForm({view,busy,act}:{view:View;busy:boolean;act:EditorProps['act']}){const [weekday,setWeekday]=useState(String(view.club.weekday));return <form className="form-stack" onSubmit={e=>{e.preventDefault();void act({type:'club',...Object.fromEntries(new FormData(e.currentTarget)),weekday:Number(weekday)},'모임 기본 정보를 저장했어요.')}}><Field label="모임 이름"><Input name="name" defaultValue={view.club.name} maxLength={40} required/></Field><Field label="기본 장소"><Input name="location" defaultValue={view.club.location} maxLength={100} required/></Field><Field label="위치"><Input name="address" defaultValue={view.club.address} maxLength={200} required/></Field><Field label="운동 요일"><Picker value={weekday} onChange={setWeekday} label="운동 요일" items={'일월화수목금토'.split('').map((n,i)=>({value:String(i),label:`${n}요일`}))}/></Field><div className="form-row"><Field label="시작 시간"><Input name="startTime" type="time" defaultValue={view.club.startTime} required/></Field><Field label="종료 시간"><Input name="endTime" type="time" defaultValue={view.club.endTime} required/></Field></div><p className="helper">이미 만든 회차의 시간·장소는 바뀌지 않아요. 해당 회차에서 따로 수정해 주세요.</p><Button disabled={busy} type="submit">모임 정보 저장</Button></form>}
function SideNavigation({view,role,setRole,page,links,navigate,clubId,changeClub,busy}:{view:View|null;role:Role;setRole:(r:Role)=>void;page:string;links:{id:string;name:string;icon:typeof Volleyball}[];navigate:(p:string)=>void;clubId:string;changeClub:(id:string)=>void;busy:boolean}){
 const {setOpenMobile}=useSidebar();const go=(p:string)=>{navigate(p);setOpenMobile(false)};
 return <Sidebar collapsible="icon" className="sideout-sidebar"><SidebarHeader className="side-brand"><span className="brand sidebar-expanded"><Volleyball/><span>SIDEOUT<small>사이드아웃</small></span></span><SidebarTrigger className="side-collapse" aria-label="사이드바 접기 또는 펼치기" title="사이드바 접기 / 펼치기"/></SidebarHeader><div className="side-club sidebar-expanded"><span className="nav-caption">나의 모임</span><strong>{EXAMPLE_CLUBS.find(c=>c.id===view?.homeClubId)?.name??'무소속'}</strong></div><SidebarContent><SidebarMenu className="side-menu">{links.map(l=><SidebarMenuItem key={l.id}><SidebarMenuButton className="nav-btn" isActive={page===l.id} tooltip={l.name} onClick={()=>go(l.id)}><l.icon/><span>{l.name}</span></SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu></SidebarContent><SidebarFooter className="side-footer"><div className="sidebar-expanded demo-role"><span><FlaskConical size={14}/>샘플 모임 · 화면 체험</span><Picker label="체험 역할" value={role} disabled={busy} items={(Object.keys(roleNames) as Role[]).map(r=>({value:r,label:`${roleNames[r]} 화면`}))} onChange={r=>setRole(r as Role)}/></div><button className={`sidebar-account ${page==='account'?'selected':''}`} title="내 계정 정보" onClick={()=>go('account')}><span className="avatar">{(view?.myName??'김나래').slice(-2)}</span><span className="sidebar-expanded grow"><strong>{view?.myName??'김나래'}</strong><small>{EXAMPLE_CLUBS.find(c=>c.id===view?.homeClubId)?.name??'무소속'} · 계정 정보</small></span><ChevronRight className="sidebar-expanded" size={16}/></button></SidebarFooter><SidebarRail/></Sidebar>
}
function AccountScreen({view,role,busy,act}:{view:View;role:Role;busy:boolean;act:(a:Action,m?:string)=>Promise<boolean>}){return <section className="panel account-panel"><div className="profile-name"><span className="avatar">{view.myName.slice(-2)}</span><div><h2>{view.myName}</h2><p className="muted">{roleNames[role]} · 샘플 계정</p></div></div><form className="form-stack" onSubmit={e=>{e.preventDefault();void act({type:'account',...Object.fromEntries(new FormData(e.currentTarget))},'내 정보를 저장했어요.')}}><Field label="표시 이름"><Input name="name" required maxLength={30} defaultValue={view.account?.name??view.myName}/></Field><Field label="한 줄 소개"><Textarea name="bio" maxLength={300} defaultValue={view.account?.bio??''} placeholder="함께 배구할 사람들에게 나를 소개해 주세요."/></Field><Field label="소속 모임"><div className="account-clubs"><LockKeyhole size={15}/>{EXAMPLE_CLUBS.find(c=>c.id===view.homeClubId)?.name??'무소속'}</div></Field><div className="form-submit"><Button disabled={busy} type="submit">계정 정보 저장</Button></div></form><p className="helper mt-6">현재는 화면 체험용 계정이에요. 실제 로그인·비밀번호 관리는 회원 계정 기능에서 연결합니다.</p></section>}
