import React from 'react';import{createRoot}from'react-dom/client';
import{ChevronLeft,ChevronRight,Star,SlidersHorizontal,Info,LockKeyhole,Check,CalendarDays,Plus,Pencil}from'lucide-react';
import{Button}from'@/components/ui/button';import{Card}from'@/components/ui/card';import{Badge}from'@/components/ui/badge';import{Progress}from'@/components/ui/progress';import './src/styles.css';
const clubs=[{id:'heroes',name:'히어로즈',mark:'H',day:5,entry:'08:00',start:'08:30',place:'시험 체육관'},{id:'nb',name:'뉴배동',mark:'N',day:6,entry:'08:00',start:'08:30',place:'시험 체육관'},{id:'asp',name:'아스팍',mark:'A',day:6,entry:'13:00',start:'13:30',place:'시험 체육관'}];
const sessions=clubs.map((club,i)=>({id:club.id,club,date:i===0?'2026-10-03':'2026-10-04',offset:0,phase:i===1?'open':'unregistered'}));
const offset=0,filter='all',favorites=new Set(),access={},REVIEW_NOW='2026-09-30T09:00';
const dateAt=(_o,d=0)=>new Date(Date.UTC(2026,8,28+d));const formatDate=date=>{const d=typeof date==='string'?new Date(date):date;return `${d.getUTCMonth()+1}월 ${d.getUTCDate()}일`};const weekLabel=()=> '10월 1째 주';
const noop=()=>{},changeWeek=noop,openFavorites=noop,openDetail=noop,setRoster=noop,toggleAttend=noop;
const canManage=()=>true,isOwn=()=>false,isPreparing=s=>s.phase!=='open',total=()=>18,progress=n=>n/24*100,published=()=>true,confirmed=()=>false,assigned=()=>false,rosterWaiters=()=>[],registrationMode=()=> 'waiting',sessionDeadline=()=>'';
function Mark({club}){return <span className={`club-mark ${club.id}`}>{club.mark}</span>}
function AttendanceButtons({s,detail=false}:{s:Session;detail?:boolean}){
 if(s.offset<0)return detail?null:<div className="event-actions"><Button size="sm" onClick={()=>openDetail(s,true)} disabled={!published(s)}>팀편성 확인</Button></div>;
 if(isPreparing(s))return <div className="event-actions"><Button size="sm" variant="outline" aria-label={`${s.club.name} ${s.phase==='draft'?'이어서 준비':'모임 등록'}`} onClick={()=>openDetail(s)}>{s.phase==='draft'?<Pencil/>:<Plus/>}{s.phase==='draft'?'이어서 준비':'모임 등록'}</Button></div>;
 const mode=registrationMode(published(s),sessionDeadline(s),REVIEW_NOW),locked=confirmed(s)&&mode==='waiting',pending=rosterWaiters(s).some(p=>p.id==='김나래')&&!assigned(s),ended=s.date+'T'+s.club.start<=REVIEW_NOW;
 return <div className="attendance-controls"><div className="event-actions"><Button size="sm" variant={confirmed(s)||pending?'outline':'default'} disabled={locked||pending||ended} onClick={()=>toggleAttend(s)}>{locked?<><LockKeyhole/>취소 불가</>:confirmed(s)?'참석 취소':pending?'대기 등록 완료':ended?'접수 종료':mode==='waiting'?'대기자 등록':'참석 신청'}</Button>{confirmed(s)&&!detail&&<Button size="sm" disabled={!published(s)} onClick={()=>openDetail(s,true)}>팀편성 확인</Button>}</div></div>
}
function Count({s}:{s:Session}){return <div className={`count-block ${s.club.id}`}><div className="count-row"><strong>{total(s)}<small>명</small></strong>{(isOwn(s)||canManage(access,s.club.id))&&!isPreparing(s)&&<Button variant="link" size="sm" onClick={()=>setRoster(s)}>명단 확인</Button>}</div><Progress value={progress(total(s))} aria-label={`참여 인원 ${total(s)}명`}/></div>}
function EventCard({s}:{s:Session}){return <Card className={`event-card ${s.club.id} ${isOwn(s)?'is-own':''} state-${s.phase??'open'}`}><div className="event-heading"><div><Mark club={s.club}/><h3>{s.club.name}</h3>{isOwn(s)&&<span className="own-label">내 모임</span>}</div>{s.offset>=0&&!isPreparing(s)&&<Button variant="ghost" size="sm" className="detail-button" aria-label={`${s.club.name} 상세 정보`} onClick={()=>openDetail(s)}><Info/>상세</Button>}{s.offset<0&&<Badge variant="secondary"><Check/>참석</Badge>}</div><p className="place">{s.club.place}</p>{isPreparing(s)?<div className={`count-block count-placeholder ${s.club.id}`} aria-label="모집 전, 신청 인원 없음"><div className="count-row"><strong aria-hidden="true">—<small>명</small></strong><span>모집 전</span></div><div className="placeholder-progress" aria-hidden="true"/></div>:Count({s})}{AttendanceButtons({s})}</Card>}
function WeekCalendar(){const days=[5,6].filter(d=>filter==='all'||sessions.some(s=>s.club.day===d));const bands=[{label:'오전',test:(s:Session)=>s.club.entry<'12:00'},{label:'오후',test:(s:Session)=>s.club.entry>='12:00'}].filter(b=>filter==='all'||sessions.some(b.test));return <><div className="week-toolbar"><h2 aria-live="polite" aria-atomic="true">{weekLabel(offset)}</h2><div><Button variant="outline" size="icon" aria-label="이전 주" onClick={()=>changeWeek(offset-1)}><ChevronLeft/></Button><Button variant={offset===0?"secondary":"outline"} size="sm" className="current-week-button" disabled={offset===0} aria-label={offset===0?"이번 주를 보고 있어요":"이번 주로 돌아가기"} onClick={()=>changeWeek(0)}>{offset===0&&<Check aria-hidden="true"/>}{offset===0?"이번 주":"이번 주로"}</Button><Button variant="outline" size="icon" aria-label="다음 주" onClick={()=>changeWeek(offset+1)}><ChevronRight/></Button></div></div><div className="week-strip">{['월','화','수','목','금','토','일'].map((d,i)=><div key={d} className={`${i>4?'weekend':''} ${offset===0&&i===2?'today':''}`}><span>{d}</span><b>{dateAt(offset,i).getUTCDate()}</b><small>{offset===0&&i===2?'오늘':i>4?`${sessions.filter(s=>s.club.day===i&&!isPreparing(s)).length}개`:''}</small></div>)}</div>{filter==='favorites'&&favorites.size>0&&<div className="mobile-favorite-tools"><Button variant="outline" size="sm" onClick={openFavorites}><SlidersHorizontal/>즐겨찾기 수정</Button></div>}{offset<0&&<div className="archive-label"><Check/>내가 참석한 운동</div>}{!sessions.length?<div className="empty-state"><CalendarDays/><h2>{filter==='favorites'&&!favorites.size?'즐겨찾는 모임을 선택해 주세요.':offset<0?'이 주에는 참석한 운동이 없어요.':'이 주에는 등록된 운동이 없어요.'}</h2>{filter==='favorites'&&!favorites.size?<Button className="empty-favorites-action" onClick={openFavorites}><Star/>즐겨찾는 모임 선택</Button>:<p>{offset<0?'다른 주의 참석 기록을 확인해 보세요.':'이전·다음 주로 이동할 수 있어요.'}</p>}</div>:<><div className={`week-board ${days.length===1?'one-day':''}`}><div className="board-heading"><span/>{days.map(d=><h3 key={d}>{d===5?'토요일':'일요일'}<small>{formatDate(dateAt(offset,d))}</small></h3>)}</div>{bands.map(b=><div className="time-band" key={b.label}><span className="band-title">{b.label}</span>{days.map(d=><div className="day-events" key={d}>{sessions.filter(s=>s.club.day===d&&b.test(s)).map(s=><div key={s.id}><p className="start-time">{s.club.entry} 입장 가능</p>{EventCard({s})}</div>)}{!sessions.some(s=>s.club.day===d&&b.test(s))&&<p className="blank-cell">표시할 운동 없음</p>}</div>)}</div>)}</div><div className="mobile-agenda">{[5,6].map(d=>sessions.some(s=>s.club.day===d)&&<section key={d}><h3>{d===5?'토요일':'일요일'}<small>{formatDate(dateAt(offset,d))}</small></h3>{sessions.filter(s=>s.club.day===d).map(s=><div className="mobile-event" key={s.id}><span>{s.club.entry}<small>입장 가능</small></span>{EventCard({s})}</div>)}</section>)}</div></>}</>}
createRoot(document.getElementById('root')!).render(<main style={{marginLeft:0,maxWidth:1280}}><WeekCalendar/></main>);