import {MatchOrder} from './match-order'
import {SessionAllocation} from './session-allocation'
import {sessionCandidates} from './session-allocation-model'
import {candidates as candidateProfiles} from './position-board-model'
import {useEffect,useRef,useState,type RefObject} from 'react'
import {Pencil,Save,Send,Plus,X,LockKeyhole,Search,Check} from 'lucide-react'
import {Button} from '@/components/ui/button'
import {Card} from '@/components/ui/card'
import {Badge} from '@/components/ui/badge'
import {Input} from '@/components/ui/input'
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog'
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select'
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from '@/components/ui/table'
import {positions,matchSchedule,type Session} from './model'
import {emptyLineup,copyLineup,assignPlayer,removePlayer,validateLineup,orderedPlayers,memberPool,groupCandidates,type Lineup,type Player,type Position,type TeamRecord} from './team-model'
import {rosterErrorMessage,type RosterCommandResult} from './roster-state'

type Props={editRequested:boolean;onBegin:()=>void;onExit:(saved?:boolean)=>void;canView:boolean;waiters:Player[];session:Session;sectionRef:RefObject<HTMLElement|null>;canEdit:boolean;canAddMembers:boolean;record?:TeamRecord;revision:number;applicants:Player[];onSave:(lineup:Lineup,publish:boolean,expectedRevision:number)=>RosterCommandResult;onDirty:(dirty:boolean)=>void;onEditing:(editing:boolean)=>void;blocked:boolean}
export function InlineTeams({editRequested,onBegin,onExit,session:s,sectionRef,canEdit,canAddMembers,record,revision,applicants,waiters,canView,onSave,onDirty,onEditing,blocked}:Props){
 const shared=record?.shared,baseline=record?.draft??shared??emptyLineup()
 const [editing,setEditing]=useState(false),[working,setWorking]=useState<Lineup>(baseline),[picker,setPicker]=useState<string|null>(null),[query,setQuery]=useState(''),[scope,setScope]=useState('unassigned'),[error,setError]=useState(''),[message,setMessage]=useState('')
 const editRef=useRef<HTMLButtonElement>(null),errorRef=useRef<HTMLParagraphElement>(null),wasEditing=useRef(false),editRevision=useRef(revision)
 const dirty=editing&&JSON.stringify(working)!==JSON.stringify(baseline)
 useEffect(()=>{onDirty(dirty)},[dirty,onDirty])
 useEffect(()=>{onEditing(editing);if(wasEditing.current&&!editing)editRef.current?.focus({preventScroll:true});if(wasEditing.current&&!editing)sectionRef.current?.scrollIntoView({block:'start'});wasEditing.current=editing},[editing,onEditing])
 useEffect(()=>()=>{onDirty(false);onEditing(false)},[onDirty,onEditing])
 useEffect(()=>{if(error)errorRef.current?.focus()},[error])
 const view=editing&&canEdit?working:canEdit&&record?.draft?record.draft:shared
 const hasPrivateDraft=!!record?.draft&&JSON.stringify(record.draft)!==JSON.stringify(shared)
 function update(next:Lineup){setWorking(next);setError('');setMessage('')}
 function begin(){editRevision.current=revision;setWorking(copyLineup(baseline));setEditing(true);setError('');setMessage('')}
 useEffect(()=>{if(editRequested&&canEdit&&!editing)begin();if((!editRequested||!canEdit)&&editing){setWorking(copyLineup(baseline));setEditing(false);setError('')}},[editRequested,canEdit])
 function cancel(){onExit()}
 function commit(publish:boolean){if(!canEdit)return;const issue=publish?validateLineup(working):'';if(issue){setError(issue);return}const result=onSave(working,publish,editRevision.current);if(!result.ok){setError(rosterErrorMessage(result.code));return}setEditing(false);setError('');setMessage(publish?'팀편성을 공개했어요.':'초안으로 저장했어요. 회원에게는 공개되지 않습니다.')}
 function openPicker(teamId:string){setQuery('');setScope('unassigned');setPicker(teamId)}
 const assignedIds=new Set(working.teams.flatMap(t=>t.players.map(p=>p.id)))
 const candidateGroups=groupCandidates(applicants,waiters,memberPool,scope==='all'&&canAddMembers).map(group=>({...group,players:group.players.filter(p=>(scope!=='unassigned'||!assignedIds.has(p.id))&&`${p.name} ${p.club} ${p.position}`.includes(query.trim()))})).filter(group=>group.players.length)
 const target=working.teams.find(t=>t.id===picker)
 function move(player:Player,teamId:string){update(assignPlayer(working,teamId,player))}
 if(!canView)return <section className="team-section inline-teams" ref={sectionRef} tabIndex={-1}><div className="section-heading"><h2>팀편성</h2></div><div className="pending"><LockKeyhole/><h3>참석자만 팀편성을 확인할 수 있어요.</h3>{waiters.length>0&&<p>대기자는 공개된 팀편성에 배정된 후 확인할 수 있어요.</p>}</div></section>
 if(editing&&canEdit)return <SessionAllocation title={`${s.club.name} · ${s.date} 팀편성`} baseline={baseline} people={sessionCandidates(applicants,waiters,baseline.teams.flatMap(t=>t.players),canAddMembers?memberPool:[],candidateProfiles)} saved={!!record?.draft||!!shared} onCancel={cancel} onDirty={onDirty} onSave={(next,publish)=>{const result=onSave(next,publish,editRevision.current);if(result.ok){setMessage(publish?'팀편성을 공개했어요.':'초안으로 저장했어요.');onExit(true)}return result}}/>
 return <section className={`team-section inline-teams ${editing?'is-editing':''}`} ref={sectionRef} tabIndex={-1}>
  <div className="section-heading team-section-heading"><div><h2>{s.offset<0?'당시 공개된 팀편성':'팀편성'}</h2>{canEdit&&hasPrivateDraft&&!editing&&<span className="draft-label">저장된 초안</span>}</div><div className="team-section-actions">{canEdit?(editing?<><Button size="sm" variant="outline" disabled={!dirty&&!!(record?.draft||shared)} onClick={cancel}>취소</Button><Button size="sm" variant="outline" onClick={()=>commit(false)}><Save/>저장</Button><Button size="sm" onClick={()=>commit(true)}><Send/>공개</Button></>:<Button ref={editRef} size="sm" variant="outline" disabled={blocked} onClick={onBegin} aria-label="팀편성 수정"><Pencil/>팀편성 수정</Button>):<span>{shared?`${shared.teams.length}팀`:'공개 전'}</span>}</div></div>
  {message&&<p className="team-feedback" role="status"><Check/>{message}</p>}
  {error&&<p className="registration-errors" ref={errorRef} tabIndex={-1} role="alert">{error}</p>}
  {editing&&<div className="lineup-toolbar"><p>저장은 운영진 초안, 공개는 회원에게 반영됩니다.</p><Button variant="outline" size="sm" disabled={working.teams.length>=4} onClick={()=>{const id=['A','B','C','D'].find(id=>!working.teams.some(t=>t.id===id))!;update({teams:[...working.teams,{id,title:id+'팀',players:[]}]})}}><Plus/>팀 추가</Button></div>}
  {!view?<><div className="pending"><LockKeyhole/><h3>아직 팀편성이 공개되지 않았어요.</h3><p>공개되면 이곳에서 팀과 경기 순서를 확인할 수 있어요.</p></div><p className="preview-note">화면 구성 예시</p><div className="team-grid preview">{['A','B','C'].map(t=><Card className="team-card" key={t}><header><h3>팀 이름</h3></header><div className="team-roster">{['세터','레프트','레프트','센터','센터','라이트','라이트'].map((pos,i)=><div className={`team-member preview-member ${i===0?'is-setter':''}`} key={i}><span className="placeholder-line"/><span className="member-position">{pos}</span></div>)}</div></Card>)}</div></>:<>
   <div className={`team-grid ${editing?'lineup-edit-grid':''}`}>{view.teams.map(team=><Card className="team-card" key={team.id}><header><h3>{team.title}</h3><Badge variant="secondary">{team.players.length}명</Badge></header>{!editing&&<div className="roster-columns" aria-hidden="true"><span>이름</span><span>소속</span><span>포지션</span></div>}<div className="team-roster">{orderedPlayers(team.players).map(player=>editing?<div className={`lineup-member ${player.position==='세터'?'is-setter':''}`} key={player.id}><div className="lineup-person"><strong>{player.name}{waiters.some(p=>p.id===player.id)&&<small className="waiting-label">대기</small>}</strong><span>{player.club}</span></div><Select value={player.position} onValueChange={value=>move({...player,position:value as Position},team.id)}><SelectTrigger aria-label={`${team.title} ${player.name} 포지션`}><SelectValue/></SelectTrigger><SelectContent>{positions.map(pos=><SelectItem key={pos} value={pos}>{pos}</SelectItem>)}</SelectContent></Select><Button size="icon" variant="ghost" aria-label={`${team.title} ${player.name} 배정 해제`} onClick={()=>update(removePlayer(working,player.id))}><X/></Button></div>:<div className={`team-member ${player.position==='세터'?'is-setter':''} ${player.name==='김나래'?'is-me':''}`} key={player.id}><span className="member-name"><span className="member-text">{player.name}</span>{player.name==='김나래'&&<Badge variant="secondary">나</Badge>}</span><span className={`member-affiliation ${player.club===s.club.name?'home-affiliation':''}`}>{player.club}</span><span className="member-position">{player.position}</span></div>)}</div>{editing&&<div className="lineup-team-actions"><Button variant="outline" size="sm" onClick={()=>openPicker(team.id)} aria-label={`${team.title} 인원 추가`}><Plus/>인원 추가</Button>{!team.players.length&&working.teams.length>1&&<Button size="sm" variant="ghost" aria-label={`${team.title} 빈 팀 삭제`} onClick={()=>update({teams:working.teams.filter(t=>t.id!==team.id)})}>빈 팀 삭제</Button>}</div>}</Card>)}</div>
   {editing&&<p className="lineup-count">배정 {working.teams.reduce((n,t)=>n+t.players.length,0)}명 · 미배정 신청자 {applicants.filter(p=>!assignedIds.has(p.id)).length}명 · 대기자 {waiters.length}명</p>}
  </>}
  {(shared||view&&!validateLineup(view))&&<MatchOrder teamCount={(view??shared)!.teams.length}/>}
  <Dialog open={!!picker} onOpenChange={open=>!open&&setPicker(null)}><DialogContent className="lineup-picker"><DialogHeader><DialogTitle>{target?.title} 인원 추가</DialogTitle><DialogDescription>선택한 인원을 배정합니다. 다른 팀에 배정된 인원은 이동합니다.</DialogDescription></DialogHeader><div className="lineup-search"><Search aria-hidden="true"/><Input value={query} onChange={e=>setQuery(e.target.value)} placeholder="이름, 소속, 포지션 검색" aria-label="편성 인원 검색"/></div><div className="lineup-filters" role="group" aria-label="편성 후보 범위">{[['unassigned','미배정'],['applied','신청자·대기자'],...(canAddMembers?[['all','모든 회원']]:[])].map(([value,label])=><Button size="sm" variant={scope===value?'secondary':'outline'} aria-pressed={scope===value} key={value} onClick={()=>setScope(value)}>{label}</Button>)}</div><div className="lineup-candidates">{candidateGroups.map(group=><section className="candidate-group" key={group.label}><h3>{group.label}<span>{group.players.length}명</span></h3>{group.players.map(player=>{const current=working.teams.find(t=>t.players.some(p=>p.id===player.id));return <Button key={player.id} className="lineup-candidate" variant="ghost" disabled={current?.id===picker} onClick={()=>{move(player,picker!);setPicker(null)}} aria-label={`${player.name} ${current?current.id===picker?'배정됨':target?.title+'으로 이동':target?.title+'에 배정'}`}><span><strong>{player.name}</strong><small>{player.club} · {player.position}</small></span><span>{current?current.id===picker?'배정됨':`${current.title} → ${target?.title}`:'추가'}<Plus/></span></Button>})}</section>)}{!candidateGroups.length&&<p className="lineup-empty">조건에 맞는 인원이 없습니다.</p>}</div></DialogContent></Dialog>
 </section>
}
