import {clubs,fixtures,iso,dateAt,type Club,type Session} from './model'
export const REVIEW_NOW='2026-09-23T12:00'
export type RegistrationForm={clubId:string;date:string;place:string;entry:string;start:string;end:string;priority:boolean;priorityUntil:string;deadline:string;capped:boolean;cap:string;notice:string}
export type RegistrationRecord={id:string;form:RegistrationForm;status:'draft'|'open'}
export type OperatorRole='master'|'chair'|'staff'
export type Access={master:boolean;managedClubIds:string[]}
export function accessForAccount(role:'master'|'operator'|'member',homeClubId:string|null,extraClubIds:string[]=[]):Access{return {master:role==='master',managedClubIds:role==='operator'?[...new Set([...(homeClubId?[homeClubId]:[]),...extraClubIds])]:[]}}
export const formChanged=(form:RegistrationForm,original:RegistrationForm)=>Object.keys(original).some(key=>form[key as keyof RegistrationForm]!==original[key as keyof RegistrationForm])
export const canManage=(access:Access,clubId:string)=>access.master||access.managedClubIds.includes(clubId)
export function nextAvailableDate(club:Club,records:RegistrationRecord[]){const d=new Date('2026-09-23T00:00:00Z');for(let i=0;i<370;i++){d.setUTCDate(d.getUTCDate()+1);const date=iso(d);if((d.getUTCDay()+6)%7===club.day&&!fixtures.some(s=>s.club.id===club.id&&s.date===date)&&!records.some(r=>r.form.clubId===club.id&&r.form.date===date))return date}return ''}
export function daysBefore(date:string,days:number){const d=new Date(date+'T00:00:00Z');if(!Number.isFinite(d.getTime()))return '';d.setUTCDate(d.getUTCDate()-days);return iso(d)}
export function defaults(club:Club,records:RegistrationRecord[]=[]):RegistrationForm{const date=nextAvailableDate(club,records);return {clubId:club.id,date,place:club.place,entry:club.entry,start:club.start,end:club.end,priority:true,priorityUntil:daysBefore(date,2)+'T18:00',deadline:daysBefore(date,1)+'T18:00',capped:false,cap:'24',notice:''}}
export function validateRegistration(f:RegistrationForm,role:OperatorRole,records:RegistrationRecord[],editing:string|null,managedClubIds:string[]=['nb'],original?:RegistrationForm){const errors:string[]=[];if(role!=='master'&&!managedClubIds.includes(f.clubId))errors.push('담당 모임의 운동만 등록할 수 있어요.');if(!clubs.some(c=>c.id===f.clubId))errors.push('모임을 선택해 주세요.');if(!/^\d{4}-\d{2}-\d{2}$/.test(f.date)||!Number.isFinite(Date.parse(f.date)))errors.push('운동 날짜를 입력해 주세요.');if(!f.place.trim())errors.push('장소를 입력해 주세요.');if(![f.entry,f.start,f.end].every(t=>/^\d{2}:\d{2}$/.test(t))||f.entry>f.start||f.start>=f.end)errors.push('입장 → 운동 시작 → 종료 순서로 시간을 확인해 주세요.');if(f.date+'T'+f.start<=REVIEW_NOW)errors.push('이미 시작한 운동은 등록할 수 없어요.');if(!f.deadline||f.deadline<=REVIEW_NOW&&f.deadline!==original?.deadline||f.deadline>=f.date+'T'+f.start)errors.push('신청 마감은 현재 시각 이후, 운동 시작 전으로 지정해 주세요.');if(f.priority&&(!f.priorityUntil||f.priorityUntil<=REVIEW_NOW&&f.priorityUntil!==original?.priorityUntil||f.priorityUntil>f.deadline))errors.push('우선 신청 종료는 현재 시각 이후, 일반 신청 마감 이내로 지정해 주세요.');if(f.capped&&(!/^\d+$/.test(f.cap)||Number(f.cap)<1||Number(f.cap)>200))errors.push('일반 신청 상한은 1~200명의 정수로 입력해 주세요.');if(fixtures.some(s=>s.id!==editing&&s.club.id===f.clubId&&s.date===f.date)||records.some(r=>r.id!==editing&&r.form.clubId===f.clubId&&r.form.date===f.date))errors.push('이 모임은 같은 날짜에 이미 등록된 운동이 있어요.');return errors}

export const isFixtureSession=(id:string)=>fixtures.some(s=>s.id===id)
export const defaultNotice=(s:Session)=>`실내 운동화와 개인 물을 챙겨 주세요.\n${s.club.entry}부터 입장해 몸을 풀고, ${s.club.start}에 운동을 시작합니다.`
export const sessionDeadline=(s:Session)=>s.registration?.deadline??daysBefore(s.date,1)+(isFixtureSession(s.id)&&s.club.id==='nb'?'T14:00':'T18:00')
export function formForSession(s:Session):RegistrationForm{return {clubId:s.club.id,date:s.date,place:s.club.place,entry:s.club.entry,start:s.club.start,end:s.club.end,priority:s.registration?!!s.registration.priorityUntil:true,priorityUntil:s.registration?.priorityUntil??daysBefore(s.date,2)+'T18:00',deadline:sessionDeadline(s),capped:s.registration?.cap!=null,cap:String(s.registration?.cap??24),notice:s.registration?.notice??(isFixtureSession(s.id)?defaultNotice(s):'')}}
export function recordSession(r:RegistrationRecord):Session{const c=clubs.find(c=>c.id===r.form.clubId)!;const baseline=fixtures.find(s=>s.id===r.id);const d=new Date(r.form.date+'T00:00:00Z');const day=(d.getUTCDay()+6)%7;return {id:r.id,recordId:r.id,club:{...c,day,place:r.form.place,entry:r.form.entry,start:r.form.start,end:r.form.end},date:r.form.date,offset:Math.floor((d.getTime()-dateAt(0).getTime())/(7*86400000)),attended:baseline?.attended??false,published:baseline?.published??false,count:baseline?.count??0,phase:r.status,registration:{deadline:r.form.deadline,priorityUntil:r.form.priority?r.form.priorityUntil:null,cap:r.form.capped?Number(r.form.cap):null,notice:r.form.notice}}}
export function calendarSessions(offset:number,filter:string,favorites:Set<string>,access:Access,records:RegistrationRecord[]):Session[]{
 const start=iso(dateAt(offset)),end=iso(dateAt(offset,6));
 const result=fixtures.filter(s=>!records.some(r=>r.id===s.id)&&s.offset===offset&&(offset>=0||s.attended));
 for(const r of records){if(r.form.date<start||r.form.date>end||r.status==='draft'&&!canManage(access,r.form.clubId))continue;const s=recordSession(r);if(offset<0&&!s.attended)continue;result.push(s)}
 if(offset>=0)for(const c of clubs){const date=iso(dateAt(offset,c.day));if(!canManage(access,c.id)||date+'T'+c.start<=REVIEW_NOW||result.some(s=>s.club.id===c.id&&s.date===date))continue;result.push({id:`new-${date}-${c.id}`,club:c,date,offset,attended:false,published:false,count:0,phase:'unregistered'})}
 return result.filter(s=>filter==='all'||filter==='favorites'&&favorites.has(s.club.id)||s.club.id===filter).sort((a,b)=>(a.date+a.club.entry).localeCompare(b.date+b.club.entry));
}
