import {useEffect,useRef,useState,type FormEvent} from 'react'
import {CalendarPlus,ChevronDown,ChevronUp,Clock3,MapPin,Check,ArrowRight,Plus} from 'lucide-react'
import {Button} from '@/components/ui/button'
import {Card} from '@/components/ui/card'
import {Badge} from '@/components/ui/badge'
import {Input} from '@/components/ui/input'
import {Textarea} from '@/components/ui/textarea'
import {Checkbox} from '@/components/ui/checkbox'
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select'
import {clubs,formatDate} from './model'
import {defaults,daysBefore,validateRegistration,type RegistrationForm,type RegistrationRecord,type OperatorRole} from './registration-model'
const pretty=(v:string)=>v?`${formatDate(v.slice(0,10))} ${v.slice(11,16)}`:'미설정'
export function RegistrationPage({records,onSave}:{records:RegistrationRecord[];onSave:(record:RegistrationRecord)=>void}){
 const [role,setRole]=useState<OperatorRole>('master'),[form,setForm]=useState(()=>defaults(clubs[3],records)),[editing,setEditing]=useState<string|null>(null),[expanded,setExpanded]=useState(false),[errors,setErrors]=useState<string[]>([]),[result,setResult]=useState<RegistrationRecord|null>(null)
 const heading=useRef<HTMLHeadingElement>(null),errorRef=useRef<HTMLDivElement>(null),resultRef=useRef<HTMLDivElement>(null)
 const club=clubs.find(c=>c.id===form.clubId)!,allowed=role==='master'?clubs:[clubs[3]],saved=records.filter(r=>role==='master'||r.form.clubId==='nb')
 useEffect(()=>{heading.current?.focus({preventScroll:true});window.scrollTo(0,0)},[])
 useEffect(()=>{if(errors.length)errorRef.current?.focus()},[errors])
 useEffect(()=>{if(result)resultRef.current?.focus()},[result])
 function change<K extends keyof RegistrationForm>(key:K,value:RegistrationForm[K]){setForm(f=>({...f,[key]:value}));setResult(null);setErrors([])}
 function reset(clubId=form.clubId){setForm(defaults(clubs.find(c=>c.id===clubId)!,records));setEditing(null);setErrors([]);setResult(null);setExpanded(false)}
 function changeRole(value:OperatorRole){setRole(value);reset(value==='master'?form.clubId:'nb')}
 function save(status:'draft'|'open'){const issues=validateRegistration(form,role,records,editing);if(issues.length){setErrors(issues);return}const record={id:editing??crypto.randomUUID(),form:{...form,place:form.place.trim(),notice:form.notice.trim()},status};onSave(record);setResult(record);setEditing(record.id);setErrors([])}
 function submit(e:FormEvent){e.preventDefault();save('open')}
 function load(record:RegistrationRecord){setForm({...record.form});setEditing(record.id);setResult(null);setErrors([]);heading.current?.focus();window.scrollTo(0,0)}
 const locked=result?.status==='open'
 return <section className="registration-page"><header className="registration-heading"><div><h1 ref={heading} tabIndex={-1}>운동 등록</h1><p>정기 일정을 불러와 다음 운동을 준비하세요.</p></div><div className="operator-preview"><label id="role-label">운영 권한 미리보기</label><Select value={role} onValueChange={v=>changeRole(v as OperatorRole)}><SelectTrigger aria-labelledby="role-label"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="master">마스터 · 전체 모임</SelectItem><SelectItem value="chair">회장 · 뉴배동</SelectItem><SelectItem value="staff">운영진 · 뉴배동</SelectItem></SelectContent></Select></div></header>
 <p className="registration-demo">로컬 등록 목업 · 2026년 9월 23일 12:00 기준 · 저장 내용은 새로고침하면 초기화됩니다.</p>
 <div className="registration-layout"><form className="registration-form" onSubmit={submit} noValidate>
 {errors.length>0&&<div className="registration-errors" ref={errorRef} tabIndex={-1} role="alert"><strong>입력 내용을 확인해 주세요.</strong><ul>{errors.map(e=><li key={e}>{e}</li>)}</ul></div>}
 {result&&<div className="registration-result" ref={resultRef} tabIndex={-1} role="status"><Check/><div><strong>{result.status==='draft'?'준비 중으로 저장했어요.':'모집 시작 상태로 등록했어요.'}</strong><p>{result.status==='draft'?'내용을 검토한 뒤 모집을 시작할 수 있어요.':'아래 등록 목록에서 확인할 수 있어요.'}</p></div><Button type="button" size="sm" variant="outline" onClick={()=>reset()}><Plus/>다음 운동</Button></div>}
 <fieldset disabled={locked} className="registration-section"><legend>운동 일정</legend><div className="registration-two"><div className="registration-field"><label id="club-label">모임</label>{role==='master'?<Select value={form.clubId} onValueChange={v=>reset(v)} disabled={locked}><SelectTrigger aria-labelledby="club-label"><SelectValue/></SelectTrigger><SelectContent>{allowed.map(c=><SelectItem key={c.id} value={c.id}>{c.name}</SelectItem>)}</SelectContent></Select>:<div className="assigned-club"><span className={`club-mark ${club.id}`}>{club.mark}</span>{club.name}<Badge variant="secondary">담당 모임</Badge></div>}</div><div className="registration-field"><label htmlFor="exercise-date">운동 날짜</label><Input id="exercise-date" type="date" value={form.date} min="2026-09-23" onChange={e=>{const date=e.target.value;setForm(f=>({...f,date,priorityUntil:daysBefore(date,2)+'T18:00',deadline:daysBefore(date,1)+'T18:00'}));setErrors([]);setResult(null)}}/><small>날짜를 바꾸면 신청 마감도 함께 조정됩니다.</small></div></div>
 <div className="regular-summary"><div><MapPin/><strong>{form.place||'장소 미입력'}</strong></div><p><Clock3/>{form.entry} 입장 · {form.start}–{form.end} 운동</p><Button type="button" size="sm" variant="ghost" aria-expanded={expanded} aria-controls="session-overrides" onClick={()=>setExpanded(v=>!v)}>장소·시간 변경{expanded?<ChevronUp/>:<ChevronDown/>}</Button></div>
 {expanded&&<div id="session-overrides" className="session-overrides"><div className="registration-field"><label htmlFor="exercise-place">장소</label><Input id="exercise-place" value={form.place} maxLength={100} onChange={e=>change('place',e.target.value)}/></div><div className="registration-times">{([['entry','입장'],['start','운동 시작'],['end','종료']] as const).map(([key,label])=><div className="registration-field" key={key}><label htmlFor={`exercise-${key}`}>{label}</label><Input id={`exercise-${key}`} type="time" value={form[key]} onChange={e=>change(key,e.target.value)}/></div>)}</div><small>이번 운동에만 적용됩니다. 모임의 정기 일정은 유지됩니다.</small></div>}</fieldset>
 <fieldset disabled={locked} className="registration-section"><legend>참가 신청</legend><label className="registration-check"><Checkbox checked={form.priority} onCheckedChange={v=>change('priority',v===true)}/>소속 회원 우선 기간 사용</label>{form.priority&&<div className="registration-field"><label htmlFor="priority-end">우선 신청 종료</label><Input id="priority-end" type="datetime-local" value={form.priorityUntil} onChange={e=>change('priorityUntil',e.target.value)}/><small>기간 내 신청한 정규 소속 회원은 편성 보장 대상입니다. 다른 모임 회원도 신청할 수 있어요.</small></div>}<div className="registration-field"><label htmlFor="registration-end">일반 신청 마감</label><Input id="registration-end" type="datetime-local" value={form.deadline} onChange={e=>change('deadline',e.target.value)}/></div><p className="candidate-until"><ArrowRight/>후보 접수는 {form.date?formatDate(form.date):'운동일'} {form.start}, 운동 시작까지</p><label className="registration-check"><Checkbox checked={form.capped} onCheckedChange={v=>change('capped',v===true)}/>일반 신청 상한 설정<Badge variant="secondary">{form.capped?`${form.cap||'–'}명`:'제한 없음'}</Badge></label>{form.capped&&<div className="registration-field"><label htmlFor="registration-cap">일반 신청 상한 (명)</label><Input id="registration-cap" type="number" inputMode="numeric" min={1} max={200} value={form.cap} onChange={e=>change('cap',e.target.value)}/><small>상한 이후에도 후보 신청이 가능하며, 우선 편성 보장 대상은 상한과 별개입니다.</small></div>}</fieldset>
 <fieldset disabled={locked} className="registration-section"><legend>이번 운동 공지 <span>선택</span></legend><label className="sr-only" htmlFor="exercise-notice">이번 운동 공지</label><Textarea id="exercise-notice" placeholder="이번 운동에서 따로 전달할 내용이 있다면 적어 주세요." rows={4} maxLength={2000} value={form.notice} onChange={e=>change('notice',e.target.value)}/></fieldset>
 <div className="registration-actions"><Button type="button" variant="outline" disabled={locked} onClick={()=>save('draft')}>준비로 저장</Button><Button type="submit" disabled={locked}><CalendarPlus/>모집 시작</Button></div>
 </form><aside className="registration-preview" aria-label="등록 내용 미리보기"><div className="preview-heading"><h2>등록 미리보기</h2><Badge variant="secondary">{result?.status==='open'?'모집 중':'준비 중'}</Badge></div><Card className={`registration-preview-card ${club.id}`}><div className="preview-club"><span className={`club-mark ${club.id}`}>{club.mark}</span><h3>{club.name}</h3></div><strong className="preview-date">{form.date?formatDate(form.date):'날짜를 선택하세요'}{form.date&&Number.isFinite(Date.parse(form.date))&&<span> {'일월화수목금토'[new Date(form.date+'T00:00:00Z').getUTCDay()]}요일</span>}</strong><p>{form.place||'장소를 입력하세요'}</p><div className="preview-times">{[[form.entry,'입장'],[form.start,'시작'],[form.end,'종료']].map(([time,label])=><div key={label}><span>{label}</span><strong>{time||'—'}</strong></div>)}</div><dl>{form.priority&&<div><dt>우선 신청 종료</dt><dd>{pretty(form.priorityUntil)}</dd></div>}<div><dt>일반 신청 마감</dt><dd>{pretty(form.deadline)}</dd></div><div><dt>신청 상한</dt><dd>{form.capped?`${form.cap||'—'}명`:'제한 없음'}</dd></div></dl>{form.notice&&<div className="preview-notice"><strong>이번 운동 공지</strong><p>{form.notice}</p></div>}</Card><p className="preview-caption">준비로 저장하면 신청은 열리지 않습니다.<br/>모집 시작 시 현재 시각부터 신청을 받습니다.</p></aside></div>
 <section className="created-exercises" aria-label="등록한 샘플 운동"><h2>등록한 샘플 운동 <span>{saved.length}</span></h2>{saved.length===0?<p className="muted">등록한 운동이 여기에 모입니다.</p>:<div className="created-list">{saved.map(r=><div className="created-row" key={r.id}><Badge variant="secondary">{r.status==='draft'?'준비 중':'모집 중'}</Badge><div><strong>{clubs.find(c=>c.id===r.form.clubId)?.name}</strong><span>{formatDate(r.form.date)} · {r.form.start}–{r.form.end}</span></div>{r.status==='draft'?<Button variant="outline" size="sm" onClick={()=>load(r)}>이어서 준비</Button>:<span className="created-open"><Check/>모집 시작됨</span>}</div>)}</div>}<p className="registration-demo">현재는 등록 화면 검토용입니다. 모임 홈·실제 신청 접수와는 아직 연결되지 않습니다.</p></section>
 </section>
}
