import {useRef,useState} from 'react'
import {Plus,Search,ChevronLeft,Users} from 'lucide-react'
import {Button} from '@/components/ui/button'
import {Input} from '@/components/ui/input'
import {Checkbox} from '@/components/ui/checkbox'
import {Badge} from '@/components/ui/badge'
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription,DialogFooter} from '@/components/ui/dialog'
import {formatDate,type Session} from './model'
import type {Player} from './team-model'

type RosterProps={session:Session;applicants:Player[];waiters:Player[];guestCount?:number;members:Player[];manager:boolean;canAdd:boolean;canCancel?:boolean;addingAsWaiting:boolean;onAdd:(players:Player[])=>string|undefined|void;onCancel?:(player:Player)=>string|undefined|void;onClose:()=>void}

export function RosterDialog({session,applicants,waiters,guestCount,members,manager,canAdd,canCancel=false,addingAsWaiting,onAdd,onCancel,onClose}:RosterProps){
 const [adding,setAdding]=useState(false),[query,setQuery]=useState(''),[selected,setSelected]=useState(new Set<string>()),[notice,setNotice]=useState('')
 const [cancelTarget,setCancelTarget]=useState<{player:Player;waiting:boolean}|null>(null)
 const footerAction=useRef<HTMLButtonElement>(null),cancelOpener=useRef<HTMLButtonElement|null>(null),cancelOpenerId=useRef<string|null>(null)
 const known=new Set([...applicants,...waiters].map(p=>p.id))
 const available=members.filter(p=>!known.has(p.id)),shown=available.filter(p=>`${p.name} ${p.club}`.includes(query.trim()))
 const own=applicants.filter(p=>p.club===session.club.name),guests=applicants.filter(p=>p.club!==session.club.name),guestTotal=guestCount??guests.length
 function back(){setAdding(false);setSelected(new Set());setQuery('')}
 function rows(title:string,people:Player[],waiting=false){return <section className="roster-group" key={title}><div className="roster-label"><h3>{title}</h3><Badge variant="secondary">{people.length}명</Badge></div>{people.length?<div className="roster-people">{people.map(p=><div className={`roster-person ${title==='소속 회원'?'roster-person-own':''}`} key={p.id}><div className="roster-person-copy"><strong>{p.name}{p.id==='김나래'&&<Badge variant="secondary">나</Badge>}</strong>{title!=='소속 회원'&&<small>{p.club}</small>}</div>{manager&&canCancel&&<Button ref={element=>{if(element&&cancelOpenerId.current===p.id)cancelOpener.current=element}} variant="ghost" className="roster-person-cancel" aria-label={`${p.name} ${waiting?'대기 등록':'참석 신청'} 취소`} onClick={event=>{cancelOpenerId.current=p.id;cancelOpener.current=event.currentTarget;setCancelTarget({player:p,waiting})}}>취소</Button>}</div>)}</div>:<p className="roster-empty">등록된 인원이 없습니다.</p>}</section>}
 return <Dialog open onOpenChange={open=>{if(!open){if(cancelTarget){setCancelTarget(null);return}onClose()}}}><DialogContent className={`roster-dialog ${cancelTarget?'roster-confirm-dialog':''}`}><DialogHeader><DialogTitle>{cancelTarget?`${cancelTarget.player.name} 님의 ${cancelTarget.waiting?'대기 등록':'참석 신청'}을 취소할까요?`:adding?'참가자 추가':'함께하는 회원'}</DialogTitle><DialogDescription>{cancelTarget?'취소하면 이번 운동 명단에서 제외됩니다.':`${session.club.name} · ${formatDate(session.date)} 운동`}</DialogDescription></DialogHeader>
 {cancelTarget?<><DialogFooter className="roster-confirm-footer"><Button variant="outline" onClick={()=>{setCancelTarget(null);requestAnimationFrame(()=>cancelOpener.current?.focus({preventScroll:true}))}}>돌아가기</Button><Button variant="destructive" onClick={()=>{const issue=onCancel?.(cancelTarget.player);if(issue){setNotice(issue);return}setNotice(cancelTarget.waiting?'대기 등록을 취소했어요.':'참석 신청을 취소했어요.');setCancelTarget(null);requestAnimationFrame(()=>footerAction.current?.focus({preventScroll:true}))}} aria-label={`${cancelTarget.waiting?'대기 등록':'참석 신청'} 취소 확인`}>{cancelTarget.waiting?'대기 등록 취소':'참석 신청 취소'}</Button></DialogFooter>{notice&&<p role="alert" className="roster-feedback">{notice}</p>}</>:adding?<><div className="roster-search"><Search aria-hidden="true"/><Input aria-label="회원 검색" placeholder="이름 또는 소속 모임 검색" value={query} onChange={e=>setQuery(e.target.value)}/></div><p className="roster-add-hint">{addingAsWaiting?'신청 마감·팀편성 공개 후에는 대기자로 추가됩니다.':'연락으로 참석 의사를 밝힌 회원을 선택하세요.'}</p><div className="roster-scroll" role="region" aria-label="추가 가능한 회원"><div className="roster-select-list">{shown.map(p=><label className={`roster-select-row ${selected.has(p.id)?'selected':''}`} key={p.id}><Checkbox aria-label={`${p.name} 선택`} checked={selected.has(p.id)} onCheckedChange={value=>setSelected(old=>{const next=new Set(old);value?next.add(p.id):next.delete(p.id);return next})}/><span><strong>{p.name}</strong><small>{p.club}</small></span></label>)}{!shown.length&&<p className="roster-empty">{available.length?'검색 결과가 없습니다.':'추가할 수 있는 회원이 없습니다.'}</p>}</div></div><DialogFooter className="roster-add-footer"><Button variant="outline" onClick={back}><ChevronLeft/>취소</Button><Button disabled={!selected.size} onClick={()=>{const people=available.filter(p=>selected.has(p.id));const issue=onAdd(people);if(issue){setNotice(issue);return}setNotice(`${people.length}명을 ${addingAsWaiting?'대기자':'참가자'}로 추가했어요.`);back()}}>{selected.size}명 추가</Button></DialogFooter>{notice&&<p role="alert" className="roster-feedback">{notice}</p>}</>:<>{notice&&<p role="status" className="roster-feedback">{notice}</p>}<div className="roster-scroll" role="region" aria-label="참가 명단">{rows('소속 회원',own)}{manager&&rows('게스트',guests)}{manager&&waiters.length>0&&rows('대기자',waiters,true)}</div>{!manager&&<div className="guest-summary"><Users/><span>게스트</span><strong>{guestTotal}<small>명</small></strong></div>}<DialogFooter className={canAdd?'roster-view-footer':''}>{canAdd?<><Button ref={footerAction} variant="outline" onClick={()=>{setNotice('');setAdding(true)}}><Plus/>참가자 추가</Button><Button onClick={onClose}>닫기</Button></>:<Button className="w-full" onClick={onClose}>확인</Button>}</DialogFooter></>}
 </DialogContent></Dialog>
}
